# Generated by Django 3.2.19 on 2023-06-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=300)),
                ('method', models.CharField(max_length=16)),
                ('args', models.CharField(max_length=100)),
            ],
        ),
    ]
