# Generated by Django 3.2.19 on 2023-06-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_interface_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=300)),
                ('base_url', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=300)),
                ('method', models.CharField(max_length=16)),
                ('args_json', models.CharField(max_length=1000)),
                ('response', models.CharField(max_length=1000)),
                ('assertion', models.CharField(max_length=1000)),
                ('result', models.CharField(max_length=16)),
            ],
        ),
    ]
