# Generated by Django 3.2.19 on 2023-06-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_auto_20230609_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='method',
            field=models.IntegerField(choices=[(1, 'get'), (2, 'post')], verbose_name='方法'),
        ),
    ]
