# Generated by Django 3.2.19 on 2023-06-19 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0005_alter_case_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='base_url',
        ),
        migrations.RemoveField(
            model_name='case',
            name='case_name',
        ),
        migrations.RemoveField(
            model_name='case',
            name='method',
        ),
        migrations.RemoveField(
            model_name='case',
            name='url',
        ),
        migrations.AddField(
            model_name='case',
            name='int_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='interface.interface'),
        ),
        migrations.AddField(
            model_name='case',
            name='modify_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='interface',
            name='header',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='interface',
            name='modify_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='interface',
            name='yn',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='interface',
            name='method',
            field=models.IntegerField(choices=[(1, 'get'), (2, 'post')], verbose_name='方法'),
        ),
    ]
