# Generated by Django 3.2.19 on 2023-06-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0006_auto_20230619_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='args_json',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
