# Generated by Django 3.2.19 on 2023-06-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0007_auto_20230619_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='int_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
