# Generated by Django 3.2.19 on 2023-06-19 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0008_alter_case_int_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='int_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interface.interface'),
        ),
    ]
