# Generated by Django 3.2.19 on 2023-06-20 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0009_alter_case_int_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='int_id',
            new_name='interf',
        ),
    ]
