# Generated by Django 3.2.19 on 2023-06-20 06:46

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0010_rename_int_id_case_interf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='args_json',
            field=jsonfield.fields.JSONField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='assertion',
            field=jsonfield.fields.JSONField(default=dict, max_length=1000),
        ),
    ]
