# Generated by Django 3.2.19 on 2023-06-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0011_auto_20230620_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='args_json',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='assertion',
            field=models.CharField(max_length=1000),
        ),
    ]
